### ISSUE TITLE
第三步 测试数据增强

### ISSUE THREAD

**Issue by AIwjy94** [taishan1994/eda_for_chinese_text_classification#1]
（3）生成数据增强文件
大佬我想问下这一步是不是有问题

**Comment by AIwjy94** [comment]
> （3）生成数据增强文件 大佬我想问下这一步是不是有问题

Namespace(delete_prob=0.3, input='../data/THUCNews/cnews.train.txt', insert_ratio=0.3, max_seq_len=256, num_aug=4, output='../data/THUCNews/eda_cnews.train.txt', replace_ratio=0.3, swap_ratio=0.3)
Traceback (most recent call last):
  File "aug_for_file.py", line 50, in <module>
    lines = [(i.split(sep)[1], i.split(sep)[0]) for i in lines]
  File "aug_for_file.py", line 50, in <listcomp>
    lines = [(i.split(sep)[1], i.split(sep)[0]) for i in lines]
IndexError: list index out of range

**Comment by taishan1994** [comment]
> > （3）生成数据增强文件 大佬我想问下这一步是不是有问题
> 
> Namespace(delete_prob=0.3, input='../data/THUCNews/cnews.train.txt', insert_ratio=0.3, max_seq_len=256, num_aug=4, output='../data/THUCNews/eda_cnews.train.txt', replace_ratio=0.3, swap_ratio=0.3) Traceback (most recent call last): File "aug_for_file.py", line 50, in lines = [(i.split(sep)[1], i.split(sep)[0]) for i in lines] File "aug_for_file.py", line 50, in lines = [(i.split(sep)[1], i.split(sep)[0]) for i in lines] IndexError: list index out of range

标签和文本之间是\t分隔的么。
